version: '3.8'

services:
  db:
    image: mysql:8.4.1
    container_name: to_do_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - neogrid_to_do_data:/var/lib/mysql

volumes:
  neogrid_to_do_data: